// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fbc4Cxq5duuRi8TiUjb8g3
// Component: aZDLoMh6Bd
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: tFa2TNZ_vYloM/component
import TextInput from "../../TextInput"; // plasmic-import: QQaMIPNvsru/component

import { useScreenVariants as useScreenVariantsinRvSwsjaPiuza } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: InRVSwsjaPiuza/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_next_feed_presell_ai.module.css"; // plasmic-import: fbc4Cxq5duuRi8TiUjb8g3/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: aZDLoMh6Bd/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: ky_TFUFtnWT7OL/icon
import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: nX45vKi2aPbS/icon
import UsersvgIcon from "./icons/PlasmicIcon__Usersvg"; // plasmic-import: 71nSI13PrkIu/icon
import CartsvgIcon from "./icons/PlasmicIcon__Cartsvg"; // plasmic-import: fdmDkvhnzsSt/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: qPyQ8vRdRnxI7U/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 3TUAcARibrbf/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: klcotCAudU6H/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: wE3rxZWinXv_/icon
import Searchsvg2Icon from "./icons/PlasmicIcon__Searchsvg2"; // plasmic-import: 84GdYG8OAoG/icon

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  nav?: p.Flex<"nav">;
  h1?: p.Flex<"h1">;
  textInput?: p.Flex<typeof TextInput>;
  textbox?: p.Flex<typeof TextInput>;
};

export interface DefaultHomeProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsinRvSwsjaPiuza()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <nav
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames(projectcss.all, sty.nav)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__bMAtp)}>
              <div className={classNames(projectcss.all, sty.columns__zlaeu)}>
                <div className={classNames(projectcss.all, sty.column__ytSdR)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__veczo)}
                  >
                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___5CaqO
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__nlfWl)}
                          role={"img"}
                        />
                      ) : null}

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__e6UjF
                        )}
                        component={Link}
                        href={`/`}
                        platform={"nextjs"}
                      >
                        {"Home"}
                      </p.PlasmicLink>

                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__jse5P)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__obOh9
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__fgGIz)}
                          role={"img"}
                        />
                      ) : null}

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__tuaIt
                        )}
                        component={Link}
                        href={`/blog-landing`}
                        platform={"nextjs"}
                      >
                        {"Blog"}
                      </p.PlasmicLink>

                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__q5NpO)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__hskDn)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___1Wvie)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"170px" as const}
                    src={{
                      src: "/plasmic/next_feed_presell_ai/images/image39.svg",
                      fullWidth: 300,
                      fullHeight: 105,
                      aspectRatio: 2.864865
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__xga6F)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ts0Q0)}
                  >
                    {true ? (
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__v5BTt
                        )}
                        component={Link}
                        href={"#" as const}
                        platform={"nextjs"}
                      >
                        <SearchsvgIcon
                          className={classNames(projectcss.all, sty.svg__rd1Ve)}
                          role={"img"}
                        />
                      </p.PlasmicLink>
                    ) : null}
                    {true ? (
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___23Tbo
                        )}
                        component={Link}
                        href={"#" as const}
                        platform={"nextjs"}
                      >
                        <UsersvgIcon
                          className={classNames(projectcss.all, sty.svg__yFySt)}
                          role={"img"}
                        />
                      </p.PlasmicLink>
                    ) : null}
                    {true ? (
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__px5Uw
                        )}
                        component={Link}
                        href={"#" as const}
                        platform={"nextjs"}
                      >
                        <CartsvgIcon
                          className={classNames(projectcss.all, sty.svg__yeYKa)}
                          role={"img"}
                        />
                      </p.PlasmicLink>
                    ) : null}
                  </div>
                </div>
              </div>
            </div>
          </nav>

          {true ? (
            <section className={classNames(projectcss.all, sty.section__gnieb)}>
              <div className={classNames(projectcss.all, sty.freeBox__pAp5G)}>
                <div
                  className={classNames(projectcss.all, sty.columns___2Fkq8)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___8K75W)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__y1G4B)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "We started with humble beginnings"
                          : "Coming Soon"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___18BwU
                        )}
                      >
                        {"19 - 02 - 2023"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.columns__ypvk3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__axQC
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vmjii
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__rhzAo
                              )}
                            >
                              {"32"}
                            </h2>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___32L2W
                              )}
                            >
                              {"Days"}
                            </div>
                          </p.Stack>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__d3Mud
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3HlWo
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__j3C0C
                              )}
                            >
                              {"22"}
                            </h2>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tse0H
                              )}
                            >
                              {"Hours"}
                            </div>
                          </p.Stack>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__fWujA
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qcerM
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__fnhud
                              )}
                            >
                              {"16"}
                            </h2>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__tTu0V
                              )}
                            >
                              {"Mintutes"}
                            </div>
                          </p.Stack>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___02VWj
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__l49DG
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__yQpa1
                              )}
                            >
                              {"32"}
                            </h2>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ijb9Q
                              )}
                            >
                              {"Sec"}
                            </div>
                          </p.Stack>
                        </div>
                      </p.Stack>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rlo03
                        )}
                      >
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            sty.link__wCTma
                          )}
                          component={Link}
                          platform={"nextjs"}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__gvDdu
                            )}
                            color={"sand" as const}
                            endIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___3WmCd
                                )}
                                role={"img"}
                              />
                            }
                            link={`/blog-landing`}
                            size={"compact" as const}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__lcjzw
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ie8Gd
                              )}
                            >
                              {"Blog"}
                            </div>
                          </Button>
                        </p.PlasmicLink>
                      </div>
                    </p.Stack>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <section className={classNames(projectcss.all, sty.section__uDXol)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___2ZFio)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__i7HGp
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Top Collections"
                  : "Click Below Link To Show Blogs"}
              </h2>

              <p.PlasmicLink
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  projectcss.__wab_text,
                  sty.link__f07HP
                )}
                component={Link}
                href={`/blog-landing`}
                platform={"nextjs"}
              >
                {"Click Here"}
              </p.PlasmicLink>
            </p.Stack>
          </section>

          <div className={classNames(projectcss.all, sty.freeBox__lstHv)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___1HScX)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__d72FS)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bpwZ8)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"120px" as const}
                  src={{
                    src: "/plasmic/next_feed_presell_ai/images/image39.svg",
                    fullWidth: 300,
                    fullHeight: 105,
                    aspectRatio: 2.864865
                  }}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7Eayt)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eA0Ce
                    )}
                  >
                    {
                      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Lorem Ipsum Dolor Sit Amet, Consectetur ."
                    }
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gVuO)}
                  >
                    <Icon3Icon
                      className={classNames(projectcss.all, sty.svg__hXxBt)}
                      role={"img"}
                    />

                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg___2O3Rz)}
                      role={"img"}
                    />

                    <Icon28Icon
                      className={classNames(projectcss.all, sty.svg__wqfEm)}
                      role={"img"}
                    />
                  </p.Stack>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__hTn2J)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__xzSo7
                  )}
                >
                  {"SUPPORT"}
                </h3>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__j1Q0K
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__dU3F)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0GerM
                    )}
                  >
                    {"FAQ"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__n4Qne)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__bHmOj
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__qElG)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hOpOp
                    )}
                  >
                    {"Shipping"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__bpQa0)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__hw8GI
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___8V127)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x4Jv
                    )}
                  >
                    {"Returns + Exchanges"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__yfbNu)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__l5Yd
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__sTtGx)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mJt08
                    )}
                  >
                    {"Contact Us"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__h3Ps4)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6JtJt)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__kvIz7
                  )}
                >
                  {"COMPANY"}
                </h3>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__xnby
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__xlMir)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Ah7
                    )}
                  >
                    {"Our Mission"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___5MOrq)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__zplas
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__tPzT4)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ysoeT
                    )}
                  >
                    {"Sustainability"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___9L2WN)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__tNCp
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___2FJTa)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p85Y
                    )}
                  >
                    {"Stores"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___9CuDz)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>

                <p.Stack
                  as={p.PlasmicLink}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__qpeYm
                  )}
                  component={Link}
                  platform={"nextjs"}
                >
                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__pCos)}
                      role={"img"}
                    />
                  ) : null}

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a0QLp
                    )}
                  >
                    {"Careers"}
                  </div>

                  {false ? (
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg___0GEgY)}
                      role={"img"}
                    />
                  ) : null}
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__o6EF)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__bcJmI
                  )}
                >
                  {"Newsletter"}
                </h3>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oPu0R
                  )}
                >
                  {"Lorem ipsum dolor sit amet, "}
                </div>

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__mbLfq)}
                  >
                    <TextInput
                      data-plasmic-name={"textInput"}
                      data-plasmic-override={overrides.textInput}
                      className={classNames("__wab_instance", sty.textInput)}
                      endIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__efTta)}
                          role={"img"}
                        />
                      }
                      placeholder={"Enter email  address" as const}
                      startIcon={
                        <Searchsvg2Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___0KHqa
                          )}
                          role={"img"}
                        />
                      }
                    />

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__bcna7
                      )}
                      color={"sand" as const}
                      endIcon={
                        <ChecksvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___7PFmp
                          )}
                          role={"img"}
                        />
                      }
                      size={"compact" as const}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__d3HFk)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yEf3X
                        )}
                      >
                        {"SUbscribe"}
                      </div>
                    </Button>
                  </p.Stack>
                ) : null}
              </p.Stack>
            </p.Stack>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "nav", "h1", "textInput", "textbox"],
  nav: ["nav"],
  h1: ["h1"],
  textInput: ["textInput", "textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nav: "nav";
  h1: "h1";
  textInput: typeof TextInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHome__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    h1: makeNodeComponent("h1"),
    textInput: makeNodeComponent("textInput"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
